# -*- coding: utf-8 -*-
"""Generates analytics for data generated by fitbit-tracker.py 

Reads in fitbit data generated by the fitbit-tracker.py program and generates
a series of data insights, graphs, charts and/or tables. 

"""
import argparse
import json
import os
import os.path
import sys
import pandas as pd
import logging
import logging.handlers
import io

from os import path
from datetime import datetime 
from datetime import date
from datetime import timedelta

# Globals
__AUTHOR__ = 'David Hunter'
__VERSION__ = 'fitbit-analysis ver beta-0.1'
__LOG_NAME__ = 'fitbit-analysis.log'
__TITLE__ = 'fitebit-analysis.py'

"""
The basic flow is to:
  - Create a dataframe consiting of hh:mm:ss
  - Create a header of the date we have data for
  - Add the indvidual data to the data frame as a new column
  - We end up with a large data set that will show for the various days, what the heartrate is for each second of the day

# Initalize a dataframe that consists of HH:MM:SS as the index
rng = pd.date_range(start='00:00:00', end='23:59:59', freq='S')
base_df = pd.DataFrame(rng.strftime('%H:%M:%S')
